language: python
# command to install dependencies
install:
    pip install -r dev-requirements.txt
# command to run tests
script: coverage run --source schematics -m py.test

after_success:
    coveralls

